import random
import uuid
from locust import HttpUser, task, between


class SmartNotesMixedUser(HttpUser):
    wait_time = between(1, 3)

    def on_start(self):
        self.user = None
        self.note_id = None
        self.note_number = None
        self.task_id = None

        tg_id = random.randint(100_000_000, 999_999_999)

        auth_payload = {
            "telegram_id": tg_id,
            "username": f"user_{uuid.uuid4().hex[:8]}",
            "full_name": "Load Test User"
        }

        response = self.client.post(
            "/auth/telegram",
            json=auth_payload,
            name="POST /auth/telegram"
        )

        if response.status_code == 200:
            self.user = response.json()

            note_payload = {
                "title": f"Seed note {uuid.uuid4().hex[:6]}",
                "content": "Initial note for load testing",
                "source": "web",
                "note_type": "plain",
                "status": "active",
                "metadata_json": {"seed": True},
                "user_id": self.user["id"]
            }

            note_response = self.client.post(
                "/notes",
                json=note_payload,
                name="POST /notes [setup]"
            )

            if note_response.status_code == 201:
                note_data = note_response.json()
                self.note_id = note_data["id"]
                self.note_number = note_data["user_note_number"]

    @task(1)
    def root(self):
        self.client.get("/", name="GET /")

    @task(2)
    def health(self):
        self.client.get("/health", name="GET /health")

    @task(4)
    def get_notes(self):
        self.client.get("/notes", name="GET /notes")

    @task(2)
    def create_note(self):
        if not self.user:
            return

        payload = {
            "title": f"Load note {uuid.uuid4().hex[:6]}",
            "content": "Generated by Locust",
            "source": "web",
            "note_type": "plain",
            "status": "active",
            "metadata_json": {"load": True},
            "user_id": self.user["id"]
        }

        response = self.client.post("/notes", json=payload, name="POST /notes")
        if response.status_code == 201:
            data = response.json()
            self.note_id = data["id"]
            self.note_number = data["user_note_number"]

    @task(4)
    def get_tasks(self):
        self.client.get("/tasks", name="GET /tasks")

    @task(2)
    def create_task(self):
        if not self.user:
            return

        payload = {
            "title": f"Load task {uuid.uuid4().hex[:6]}",
            "description": "Generated by Locust",
            "priority": random.choice(["low", "medium", "high"]),
            "status": random.choice(["pending", "done"]),
            "ai_generated": False,
            "user_id": self.user["id"],
            "note_id": self.note_id
        }

        response = self.client.post("/tasks", json=payload, name="POST /tasks")
        if response.status_code == 201:
            self.task_id = response.json()["id"]

    @task(1)
    def get_single_task(self):
        if not self.task_id:
            return

        self.client.get(f"/tasks/{self.task_id}", name="GET /tasks/{id}")

    @task(1)
    def update_task(self):
        if not self.task_id:
            return

        payload = {
            "status": random.choice(["pending", "done"]),
            "priority": random.choice(["low", "medium", "high"]),
            "title": f"Updated {uuid.uuid4().hex[:4]}"
        }

        self.client.patch(
            f"/tasks/{self.task_id}",
            json=payload,
            name="PATCH /tasks/{id}"
        )

    @task(1)
    def delete_task(self):
        if not self.task_id:
            return

        response = self.client.delete(
            f"/tasks/{self.task_id}",
            name="DELETE /tasks/{id}"
        )

        if response.status_code == 204:
            self.task_id = None